
nclouds-redis:
  image: redis
  ports:
    - "6379"

nclouds1:
  build: ./nclouds-app
  ports:
    - "4000"
  links:
    - "nclouds-redis:redis.service.consul"

nclouds2:
  build: ./nclouds-app
  ports:
    - "4000"
  links:
    - "nclouds-redis:redis.service.consul"

nginx:
  build: ./nginx
  container_name: nginx
  links:
    - "nclouds1:nclouds-server-1"
    - "nclouds2:nclouds-server-2"
  ports:
    - "80:80"
